version: 2.1
orbs:
  qodana: jetbrains/qodana@2022.2.1
jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan:
          args: -e QODANA_REMOTE_URL=$CIRCLE_REPOSITORY_URL
workflows:
  main:
    jobs:
      - code-quality:
          context: qodana
